core:
  spawn_window: true
  commands_fifo: /tmp/dashboard_commands
  title:
    fifo: /tmp/status_fifo
plugins:
  media:
    - type: chrome
      port: 8888
    - type: mpd
      host: <hostname>
      port: 6600
      local_path: <local directory of music>
    - type: dummy
    - type: spotify
      token: abcdef1234567890
  bluetooth:
    - mac: 00:00:00:00:00:0A
      name: My Device
    - mac: 00:00:00:00:00:0B
      name: My Device 2
